<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ8cVTie\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ8cVTie/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ8cVTie.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ8cVTie\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ8cVTie\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z8cVTie',
    'container.build_id' => 'baf46116',
    'container.build_time' => 1570443150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ8cVTie');
